# Generated by Django 2.0 on 2019-11-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AddField(
            model_name='query',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='solution', verbose_name='imagen'),
        ),
    ]
