# Generated by Django 2.0 on 2019-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0002_auto_20191112_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='recep_model',
        ),
        migrations.RemoveField(
            model_name='query',
            name='recep_model',
        ),
        migrations.AddField(
            model_name='query',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='query',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
