# Generated by Django 2.0 on 2019-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0004_auto_20191112_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='recep_model',
            field=models.ManyToManyField(to='solution.Recepmodel', verbose_name='modelos'),
        ),
    ]
