# Generated by Django 2.0 on 2019-11-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0005_query_recep_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='recep_model',
        ),
        migrations.AddField(
            model_name='query',
            name='recep_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solution.Recepmodel', verbose_name='modelo'),
        ),
    ]
